import type { Category, Severity, Tier } from "../types";

export interface GrepExtendedRuleDefinition {
  id: string;
  pattern: RegExp;
  category: Category;
  severity: Severity;
  tier: Tier;
  message: string;
  desc: string;
  fix?: string;
  fileFilter?: RegExp;
}

export const GREP_EXTENDED_RULES: GrepExtendedRuleDefinition[] = [
  {
    id: "EMPTY_TEST",
    pattern: /^\s*(it|test)\s*\(\s*['"][^'"]+['"]\s*,\s*(\(\)|async\s*\(\))\s*=>\s*\{\s*\}\s*\)/,
    category: "test-quality",
    severity: "HIGH",
    tier: 0,
    message: "Empty test body — test passes but checks nothing",
    desc: "Empty test body — passes but checks nothing",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "WEAK_ASSERTION",
    pattern: /expect\([^)]+\)\.(toBeTruthy|toBeDefined|not\.toBeNull|not\.toBeUndefined)\(\)/,
    category: "test-quality",
    severity: "MEDIUM",
    tier: 0,
    message: "Weak assertion — tests existence not correctness. Assert on the actual value.",
    desc: "Weak assertion — tests existence not value",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "ASSERT_TRUE",
    pattern: /\b(assert\s+True|assertTrue\(true|expect\(true\)\.toBe\(true\))/,
    category: "test-quality",
    severity: "HIGH",
    tier: 0,
    message: "Tautological assertion — always passes, tests nothing",
    desc: "Tautological assert True — always passes",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx|py)$/,
  },
  {
    id: "SLEEPY_TEST",
    pattern: /\b(setTimeout|sleep|await\s+delay|await\s+new\s+Promise.*setTimeout)\s*\(/,
    category: "test-quality",
    severity: "MEDIUM",
    tier: 0,
    message: "Sleep in test — use waitFor/polling instead of arbitrary delays",
    desc: "Sleep in test — use waitFor instead",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "SKIPPED_TEST",
    pattern: /\b(it\.skip|test\.skip|xit|xdescribe|xtest|@pytest\.mark\.skip|@unittest\.skip)/,
    category: "test-quality",
    severity: "LOW",
    tier: 0,
    message: "Skipped test — resolve or remove, don't leave disabled tests",
    desc: "Skipped test — resolve or remove",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx|py)$/,
  },
  {
    id: "SNAPSHOT_OVERUSE",
    pattern: /toMatchSnapshot\(\)|toMatchInlineSnapshot\(/,
    category: "test-quality",
    severity: "LOW",
    tier: 0,
    message: "Snapshot test — brittle, breaks on any change. Assert on specific values.",
    desc: "Snapshot test — brittle, assert on values",
    fileFilter: /\.(test|spec)\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "FOREACH_ASYNC",
    pattern: /\.forEach\(\s*async\s/,
    category: "async-correctness",
    severity: "CRITICAL",
    tier: 0,
    message: "async callback in forEach — promises are fire-and-forgotten. Use for...of or Promise.all(map()).",
    desc: "async in forEach — promises fire-and-forget",
  },
  {
    id: "ASYNC_PROMISE_EXECUTOR",
    pattern: /new\s+Promise\s*\(\s*async\s*\(/,
    category: "async-correctness",
    severity: "HIGH",
    tier: 0,
    message: "async Promise executor — use a plain async function or non-async executor with explicit resolve/reject",
    desc: "async Promise executor — avoid async inside new Promise",
  },
  {
    id: "USEEFFECT_ASYNC",
    pattern: /useEffect\(\s*async\s*\(/,
    category: "async-correctness",
    severity: "HIGH",
    tier: 0,
    message: "async useEffect callback — wrap the async work in an inner function instead",
    desc: "async useEffect callback — wrap async work inside",
    fileFilter: /\.(tsx|jsx)$/,
  },
  {
    id: "REDUNDANT_RETURN_AWAIT",
    pattern: /return\s+await\s+\w+\(/,
    category: "async-correctness",
    severity: "LOW",
    tier: 0,
    message: "return await on a direct promise — return the promise unless you need try/catch semantics",
    desc: "return await on direct promise",
  },
  {
    id: "BARE_ASYNC_MAP",
    pattern: /\.map\(\s*async\s/,
    category: "async-correctness",
    severity: "HIGH",
    tier: 0,
    message: "async map result not obviously awaited — collect with Promise.all(...) or use for...of",
    desc: "async map result not obviously awaited",
  },
  {
    id: "REQUESTS_IN_ASYNC",
    pattern: /^\s*(response|r|res)\s*=\s*(requests\.(get|post|put|patch|delete))/,
    category: "async-correctness",
    severity: "CRITICAL",
    tier: 0,
    message: "Blocking requests.get/post in async context — use httpx.AsyncClient instead",
    desc: "Blocking requests in async — use httpx",
    fileFilter: /\.py$/,
  },
  {
    id: "SEQUENTIAL_AWAIT",
    pattern: /await\s+\w+\([^)]*\)\s*;\s*\n\s*(?:const|let|var)\s+\w+\s*=\s*await\s+\w+\(/,
    category: "async-correctness",
    severity: "MEDIUM",
    tier: 0,
    message: "Sequential awaits — if independent, use Promise.all() for parallel execution",
    desc: "Sequential awaits — use Promise.all()",
  },
  {
    id: "CALLBACK_PROMISE_MIX",
    pattern: /(?:^|[^/'"`])\.then\(\s*(?:async\b|(?:\([^)]*\)|\w+)\s*=>.*await\b)/,
    category: "async-correctness",
    severity: "MEDIUM",
    tier: 0,
    message: "Mixing .then() with async/await — pick one style",
    desc: "Mixing .then() with async/await",
  },
  {
    id: "JSON_DEEP_CLONE",
    pattern: /JSON\.parse\(\s*JSON\.stringify\(/,
    category: "ai-slop",
    severity: "MEDIUM",
    tier: 0,
    message: "JSON stringify/parse deep clone — lossy and slow. Use structuredClone when available.",
    desc: "JSON stringify/parse deep clone",
  },
  {
    id: "HANDWAVY_COMMENT",
    pattern: /^\s*(\/\/|#)\s*(quick fix|temporary workaround|works for now|good enough|safe enough|hacky|dirty)\b/i,
    category: "ai-slop",
    severity: "LOW",
    tier: 1,
    message: "Handwavy comment — vague workaround language leaked into code",
    desc: "Handwavy workaround comment",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "NOT_IMPLEMENTED_STUB",
    pattern: /throw\s+new\s+Error\s*\(\s*["'`](todo|not implemented|unimplemented|stub|implement me|placeholder)["'`]\s*\)/i,
    category: "ai-slop",
    severity: "MEDIUM",
    tier: 1,
    message: "Not-implemented stub shipped in JS/TS code",
    desc: "Not-implemented JS/TS stub",
    fix: "Implement the function or replace the placeholder stub",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "DEAD_FEATURE_FLAG",
    pattern: /^\s*(?:export\s+)?(?:const|let|var)\s+[A-Za-z_$][\w$]*(?:flag|feature|enabled|toggle|experiment|gate)[A-Za-z_$\d]*\s*=\s*(true|false)\s*;?\s*$/i,
    category: "legacy-code",
    severity: "MEDIUM",
    tier: 0,
    message: "Feature flag always on/off — remove the dead branch or make it real configuration",
    desc: "Feature flag always on/off",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "THROW_NON_ERROR",
    pattern: /^\s*throw\s+(?:["'`]|\{|\[|\d|true\b|false\b|null\b|undefined\b)/,
    category: "defensive-programming",
    severity: "HIGH",
    tier: 0,
    message: "Thrown value is not an Error instance — throw Error objects for stack/cause semantics",
    desc: "Thrown value is not an Error instance",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "CATCH_WRAP_NO_CAUSE",
    pattern: /^\s*throw\s+new\s+(?:Error|TypeError|RangeError|ReferenceError|SyntaxError|URIError|EvalError|AggregateError)\s*\(/,
    category: "defensive-programming",
    severity: "MEDIUM",
    tier: 0,
    message: "Catch block wraps an error without preserving the original cause",
    desc: "Catch wraps error without preserving cause",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "UNVALIDATED_BODY",
    pattern: /(?:req|request)\.body\s*(as\s+\w|:\s*\w)/,
    category: "runtime-validation",
    severity: "CRITICAL",
    tier: 0,
    message: "req.body type-cast without runtime validation — TypeScript types are erased at runtime. Use Zod/Yup/Joi.",
    desc: "req.body cast without runtime validation",
  },
  {
    id: "JSON_PARSE_CAST",
    pattern: /JSON\.parse\([^)]+\)\s*as\s+\w/,
    category: "runtime-validation",
    severity: "HIGH",
    tier: 0,
    message: "JSON.parse cast to type without validation — parse result is unknown at runtime",
    desc: "JSON.parse cast without validation",
  },
  {
    id: "FETCH_RESPONSE_CAST",
    pattern: /\.json\(\)\s*(as\s+\w|<\w)/,
    category: "runtime-validation",
    severity: "HIGH",
    tier: 0,
    message: "Fetch response cast without validation — API responses need runtime schema checks",
    desc: "Fetch response cast without validation",
  },
  {
    id: "LOCALSTORAGE_CAST",
    pattern: /localStorage\.getItem\([^)]+\)\s*(as\s+\w|!)/,
    category: "runtime-validation",
    severity: "MEDIUM",
    tier: 0,
    message: "localStorage value cast without validation — user-controlled data needs parsing",
    desc: "localStorage cast without validation",
  },
  {
    id: "INTERACTIVE_DIV",
    pattern: /<div[^>]*\sonClick/,
    category: "accessibility",
    severity: "HIGH",
    tier: 0,
    message: "onClick on <div> — use <button> for interactive elements (keyboard/screen reader accessible)",
    desc: "onClick on <div> — use <button>",
    fix: "Replace <div onClick> with <button onClick>",
    fileFilter: /\.(tsx|jsx)$/,
  },
  {
    id: "INTERACTIVE_SPAN",
    pattern: /<span[^>]*\sonClick/,
    category: "accessibility",
    severity: "HIGH",
    tier: 0,
    message: "onClick on <span> — use <button> or <a> for interactive elements",
    desc: "onClick on <span> — use <button>",
    fix: "Replace <span onClick> with <button onClick>",
    fileFilter: /\.(tsx|jsx)$/,
  },
  {
    id: "IMG_NO_ALT",
    pattern: /<img\s[^>]*(?!.*\balt\b)[^>]*>/,
    category: "accessibility",
    severity: "HIGH",
    tier: 0,
    message: "Image without alt attribute — WCAG Level A violation",
    desc: "Image without alt attribute — WCAG A",
    fix: "Add a descriptive alt attribute",
    fileFilter: /\.(tsx|jsx|html)$/,
  },
  {
    id: "MEANINGLESS_ALT",
    pattern: /alt=["'](image|photo|pic|img|icon|logo|picture|banner|figure)["']/i,
    category: "accessibility",
    severity: "MEDIUM",
    tier: 0,
    message: "Meaningless alt text — describe what the image shows, not what it is",
    desc: "Meaningless alt text (image/photo/icon)",
    fix: "Replace with descriptive alt text",
    fileFilter: /\.(tsx|jsx|html)$/,
  },
  {
    id: "INPUT_NO_LABEL",
    pattern: /<input[^>]*placeholder[^>]*(?!.*aria-label)(?!.*aria-labelledby)[^>]*\/?\s*>/,
    category: "accessibility",
    severity: "MEDIUM",
    tier: 0,
    message: "Input with placeholder but no label — placeholders are not labels",
    desc: "Input with placeholder but no label",
    fix: "Add <label htmlFor> or aria-label",
    fileFilter: /\.(tsx|jsx|html)$/,
  },
  {
    id: "NUMERIC_SUFFIX",
    pattern: /\b(const|let|var|function)\s+\w+[2-9]\s*[=(:]/,
    category: "naming-semantics",
    severity: "MEDIUM",
    tier: 0,
    message: "Numeric suffix in identifier — rename to describe what's different",
    desc: "Numeric suffix — rename to describe diff",
  },
  {
    id: "GENERIC_BUCKET_FILE",
    pattern: /^$/,
    category: "naming-semantics",
    severity: "MEDIUM",
    tier: 0,
    message: "Generic bucket file — split into domain-specific modules",
    desc: "Generic bucket file — split by domain",
  },
  {
    id: "EVAL_EXEC",
    pattern: /^\s*\w*\s*=?\s*\b(eval|exec)\s*\(/,
    category: "security-slop",
    severity: "CRITICAL",
    tier: 0,
    message: "eval()/exec() — arbitrary code execution. Use a safe parser instead.",
    desc: "eval()/exec() — arbitrary code execution",
  },
  {
    id: "PICKLE_LOADS",
    pattern: /pickle\.(loads?|Unpickler)\s*\(/,
    category: "security-slop",
    severity: "CRITICAL",
    tier: 0,
    message: "pickle.load on potentially untrusted data — use json or a safe serializer",
    desc: "pickle.load — RCE on untrusted data",
    fileFilter: /\.py$/,
  },
  {
    id: "MUTABLE_DEFAULT",
    pattern: /def\s+\w+\([^)]*=\s*(\[\]|\{\}|set\(\))/,
    category: "defensive-programming",
    severity: "HIGH",
    tier: 0,
    message: "Mutable default argument — shared across all calls. Use None and create inside.",
    desc: "Mutable default argument — shared state",
    fix: "Use None as default, create mutable object inside function body",
    fileFilter: /\.py$/,
  },
  {
    id: "BUILTIN_SHADOW",
    pattern: /\b(list|dict|set|map|filter|range|zip|all|any|sum|min|max|len|open|print|next|iter|super)\s*=\s/,
    category: "naming-semantics",
    severity: "MEDIUM",
    tier: 0,
    message: "Variable shadows Python builtin — use a more specific name",
    desc: "Variable shadows Python builtin",
    fileFilter: /\.py$/,
  },
  {
    id: "ITERROWS",
    pattern: /\.iterrows\(\)/,
    category: "complexity",
    severity: "MEDIUM",
    tier: 0,
    message: "pandas iterrows() is 100-1000x slower than vectorized operations",
    desc: "pandas iterrows — use vectorized ops",
    fix: "Use vectorized column operations or .apply()",
    fileFilter: /\.py$/,
  },
  {
    id: "FULL_LODASH_IMPORT",
    pattern: /import\s+_\s+from\s+['"]lodash['"]/
    ,category: "complexity",
    severity: "HIGH",
    tier: 0,
    message: "Full lodash import adds ~70KB gzipped — import specific functions: lodash/debounce",
    desc: "Full lodash import — import specific fns",
    fix: "import debounce from 'lodash/debounce'",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "MOMENT_IMPORT",
    pattern: /import\s+moment\s+from\s+['"]moment['"]/
    ,category: "legacy-code",
    severity: "MEDIUM",
    tier: 0,
    message: "moment.js is deprecated and 300KB — use date-fns, dayjs, or Temporal",
    desc: "moment.js deprecated — use date-fns/dayjs",
    fix: "Replace with date-fns or dayjs",
    fileFilter: /\.(ts|tsx|js|jsx)$/,
  },
  {
    id: "TAILWIND_HARDCODED_COLOR",
    pattern: /className="[^"]*\[#[0-9a-fA-F]{3,8}\]/,
    category: "inconsistency",
    severity: "LOW",
    tier: 0,
    message: "Hardcoded hex color in Tailwind — use design tokens or theme colors",
    desc: "Hardcoded hex in Tailwind className",
    fileFilter: /\.(tsx|jsx)$/,
  },
  {
    id: "INLINE_STYLE",
    pattern: /style=\{\{[^}]*(color|background|margin|padding|fontSize|fontWeight|border)/,
    category: "inconsistency",
    severity: "LOW",
    tier: 0,
    message: "Inline style for layout/color — use CSS classes or Tailwind utilities",
    desc: "Inline style for layout/color",
    fileFilter: /\.(tsx|jsx)$/,
  },
  {
    id: "MANY_USESTATE",
    pattern: /useState/,
    category: "complexity",
    severity: "MEDIUM",
    tier: 0,
    message: "Component may have too many useState calls — consider useReducer or extracting logic",
    desc: "6+ useState in one component",
    fileFilter: /^$/,
  },
];

export const GREP_EXTENDED_RULE_CATALOG = GREP_EXTENDED_RULES
  .filter((rule) => rule.pattern.source !== "^$")
  .map(({ id, category, tier, desc }) => ({ id, category, tier, tool: "grep", desc }));
